### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by KjarTalak** [furbrain/CircuitPython_seeed_xiao_nRF52840#1]
I'm getting the following Error trying to use your example Code on my SEEEDUINO XIAO Sense: 

ImportError: no module named 'circuitpython_typing'

circup is also warning, that "typing-extensions" is not a known CircuitPython-lib

Can you give me an Info on what to do to fix it?

**Comment by dhoisington** [comment]
I commented out line 41 in the .py file and it worked.

**Comment by furbrain** [comment]
Thanks - I had fixed this, but forgot to push a release. Should be fixed in v1.0.1 - otherwise fix by @dhoisington is a good workaround
